import os; os.chdir(r"D:\administrator\Documents\project\S-Protect-PY")
t = open("sprotect/loader.py", "r").read()

# Replace the entire gen_loader_source function with one that uses FIXED names
old_gen = t[t.find("def gen_loader_source"):]
old_gen = old_gen[:old_gen.find("def gen_boot")]

new_gen = '''def gen_loader_source():
    """Generate loader source with k1-k5 key system."""
    lines = [
        '# v12 k1-k5',
        'import sys,os,json,hashlib,zlib,msgpack,time,threading',
        'import importlib.abc,importlib.machinery,secrets',
        'from cryptography.hazmat.primitives.ciphers.aead import AESGCM',
        'try: _SD=os.path.dirname(os.path.abspath(__file__))',
        'except: _SD=os.path.dirname(os.path.abspath(sys.argv[0])) if sys.argv else "."',
        '_D=os.path.join(_SD,"_runtime") if os.path.isdir(os.path.join(_SD,"_runtime")) else _SD',
        '_MAP="";_BOMB=None',
        '',
        'def xf(l,s):',
        ' r,c=bytearray(),0',
        ' while len(r)<l:',
        '  r.extend(hashlib.sha256(s+c.to_bytes(4,"big")).digest());c+=1',
        ' return bytes(r[:l])',
        '',
        'def kf(p,k):',
        ' ct=bytes.fromhex(p.get("d","0"*32))',
        ' try:x=AESGCM(k).decrypt(ct[:12],ct[12:],b"");return zlib.decompress(x).decode()',
        ' except:',
        '  while True: pass',
        '',
        'def hf():return True',
        '',
        'def ac():',
        ' import sys as _s',
        ' if _s.gettrace() is not None:',
        '  def _burn():',
        '   import time as _t;_t.sleep(120);import os as _os;_os._exit(0)',
        '  t=threading.Thread(target=_burn,daemon=True);t.start()',
        ' if "pydevd" in _s.modules:',
        '  globals().update({"AESGCM":lambda:None})',
        '',
        '# k1-k5 path selector',
        'def ps(p):',
        ' f=p.get("f",0);ks=p.get("k",[])',
        ' if len(ks)<5:return 0,ks[0] if ks else b"",0',
        ' pos=(f>>3)&7;trap=(f>>7)&1',
        ' if pos>=len(ks):pos=0',
        ' return pos,ks[pos] if pos<len(ks) else ks[0],trap',
        '',
        'def dc(p,mk):',
        ' ct=p.get("d",b"")',
        ' if not ct:return "",0',
        ' _,rk,trap=ps(p)',
        ' if trap:return "",1',
        ' for k in [rk,mk]:',
        '  try:x=AESGCM(k).decrypt(ct[:12],ct[12:],b"");return zlib.decompress(x).decode(),0',
        '  except:pass',
        ' return "",0',
        '',
        '# dynamic code generator',
        'def dg(entry,mk,mmap):',
        ' mh=mk.hex()',
        ' mj=json.dumps(mmap,separators=(",",":"))',
        ' fn="_"+secrets.token_hex(6)',
        ' dc="""#dyn',
        'import sys,os,json,hashlib,zlib,msgpack',
        'from cryptography.hazmat.primitives.ciphers.aead import AESGCM',
        'import importlib.abc,importlib.machinery',
        'MK=bytes.fromhex("__MK__")',
        'MMAP=json.loads("__MJ__")',
        'RD=r"__RD__"',
        'def __F__(p,mk):',
        ' ct=p.get("d",b"");ks=p.get("k",[]);f=p.get("f",0)',
        ' if len(ks)<5:ks=ks+[b""]*(5-len(ks))',
        ' pos=(f>>3)&7',
        ' if pos>=5:pos=0;k=ks[0]',
        ' else:k=ks[pos]',
        ' if (f>>7)&1:return ""',
        ' for k2 in [k,mk]:',
        '  try:x=AESGCM(k2).decrypt(ct[:12],ct[12:],b"");return zlib.decompress(x).decode()',
        '  except:pass',
        ' return ""',
        'class _L(importlib.abc.Loader):',
        ' def __init__(s,n,p,mk,pk=False):s.n,s.p,s.mk,s.pk=n,p,mk,pk',
        ' def create_module(s,sp):return None',
        ' def exec_module(s,m):',
        '  m.__dict__.setdefault("__file__",s.p)',
        '  m.__dict__.setdefault("__package__",s.n)',
        '  if s.pk:m.__dict__.setdefault("__path__",[os.path.dirname(s.p)])',
        '  pp=msgpack.unpackb(open(s.p,"rb").read()[3:],strict_map_key=False)',
        '  pd={"d":pp.get(2,b""),"k":pp.get(3,[]),"f":pp.get(1,0)}',
        '  s2=__F__(pd,s.mk)',
        '  if s2:exec(compile(s2,s.p,"exec"),m.__dict__)',
        'class _F(importlib.abc.MetaPathFinder):',
        ' def __init__(s,mk,mmap):s.mk,s.mmap=mk,mmap',
        ' def find_spec(s,n,p=None,t=None):',
        '  hn=s.mmap.get(n,"");pye=os.path.join(RD,hn+".pye") if hn else ""',
        '  if os.path.isfile(pye):',
        '   ip=any(mn.startswith(n+".") for mn in s.mmap)',
        '   sp=importlib.machinery.ModuleSpec(n,_L(n,pye,s.mk,ip),origin=pye)',
        '   if ip:sp.submodule_search_locations=[os.path.dirname(pye)]',
        '   return sp',
        '  return None',
        'sys.meta_path.insert(0,_F(MK,MMAP))',
        'ep=os.path.join(RD,MMAP.get("__EN__","")+".pye")',
        'if os.path.isfile(ep):',
        ' pp=msgpack.unpackb(open(ep,"rb").read()[3:],strict_map_key=False)',
        ' pd={"d":pp.get(2,b""),"k":pp.get(3,[]),"f":pp.get(1,0)}',
        ' s2=__F__(pd,MK)',
        ' if s2:exec(compile(s2,ep,"exec"),{"__name__":"__main__","__file__":os.path.join(os.path.dirname(RD),"__EN__.py")})',
        '"""',
        ' dc=dc.replace("__MK__",mh).replace("__MJ__",mj.replace(\'"\',\'\\\\"\'))',
        ' dc=dc.replace("__RD__",_D).replace("__F__",fn).replace("__EN__",entry)',
        ' return dc',
        '',
        'def run(entry,root=""):',
        ' if not _MAP:raise RuntimeError("no map")',
        ' ac()',
        ' hf()',
        ' mmap=json.loads(_MAP)',
        ' shards={}',
        ' for mn,hn in mmap.items():',
        '  pye=os.path.join(_D,hn+".pye")',
        '  if not os.path.isfile(pye):continue',
        '  try:',
        '   pp=msgpack.unpackb(open(pye,"rb").read()[3:],strict_map_key=False)',
        '   pd={"d":pp.get(2,b""),"k":pp.get(3,[]),"f":pp.get(1,0)}',
        '   _,k,t=ps(pd)',
        '   if k and not t:shards[mn]=k',
        '  except:pass',
        ' if shards:',
        '  vl=list(shards.values());mk=bytearray(vl[0])',
        '  for v in vl[1:]:',
        '   for i in range(min(len(mk),len(v))):mk[i]^=v[i]',
        '  mk=bytes(mk)',
        ' else:mk=b""',
        ' dyn=dg(entry,mk,mmap)',
        ' try:exec(compile(dyn,"<gen>","exec"))',
        ' except Exception as e:raise RuntimeError("dyn:"+str(e))',
    ]
    return "\\n".join(lines)

'''

t = t.replace(old_gen, new_gen)
open("sprotect/loader.py", "w").write(t)
print("Fixed gen_loader_source")
